<!-- <?php if ($row['type'] == 'application/pdf'){ ?><a href="../download-documents.php?id=<?php echo "{$row['id']}"; ?>&docdate=<?php echo "{$row['docdate']}"; ?>&conn=<?php echo $record['dbconnName'];?>&size=<?php echo "{$row['size']}"; ?>" target="_blank" onclick="javascript:pageTracker._trackPageview('DOCUMENTS/<?php echo "{$row['id']}"; ?>'); "><img alt="" src="https://condosites.net/commons/pdf.png" style="border: 0px solid;" border="0"></a><?php }; ?> -->
<?php if ($row['type'] == 'image/jpeg'){ ?><a href="../download-documents.php?id=<?php echo "{$row['id']}"; ?>&docdate=<?php echo "{$row['docdate']}"; ?>&conn=<?php echo $record['dbconnName'];?>&size=<?php echo "{$row['size']}"; ?>" target="_blank" onclick="javascript:pageTracker._trackPageview('DOCUMENTS/<?php echo "{$row['id']}"; ?>'); "><img alt="" src="https://condosites.net/commons/pictures.png" style="border: 0px solid;" border="0"></a><?php }; ?>
<?php if ($row['type'] == 'image/pjpeg'){ ?><a href="../download-documents.php?id=<?php echo "{$row['id']}"; ?>&docdate=<?php echo "{$row['docdate']}"; ?>&conn=<?php echo $record['dbconnName'];?>&size=<?php echo "{$row['size']}"; ?>" target="_blank" onclick="javascript:pageTracker._trackPageview('DOCUMENTS/<?php echo "{$row['id']}"; ?>'); "><img alt="" src="https://condosites.net/commons/pictures.png" style="border: 0px solid;" border="0"></a><?php }; ?>
<?php if ($row['type'] == 'image/gif'){ ?><a href="../download-documents.php?id=<?php echo "{$row['id']}"; ?>&docdate=<?php echo "{$row['docdate']}"; ?>&conn=<?php echo $record['dbconnName'];?>&size=<?php echo "{$row['size']}"; ?>" target="_blank" onclick="javascript:pageTracker._trackPageview('DOCUMENTS/<?php echo "{$row['id']}"; ?>'); "><img alt="" src="https://condosites.net/commons/pictures.png" style="border: 0px solid;" border="0"></a><?php }; ?>
<?php if ($row['type'] == 'image/png'){ ?><a href="../download-documents.php?id=<?php echo "{$row['id']}"; ?>&docdate=<?php echo "{$row['docdate']}"; ?>&conn=<?php echo $record['dbconnName'];?>&size=<?php echo "{$row['size']}"; ?>" target="_blank" onclick="javascript:pageTracker._trackPageview('DOCUMENTS/<?php echo "{$row['id']}"; ?>'); "><img alt="" src="https://condosites.net/commons/pictures.png" style="border: 0px solid;" border="0"></a><?php }; ?>
<?php if ($row['type'] == 'application/rtf'){ ?><a href="../download-documents.php?id=<?php echo "{$row['id']}"; ?>&docdate=<?php echo "{$row['docdate']}"; ?>&conn=<?php echo $record['dbconnName'];?>&size=<?php echo "{$row['size']}"; ?>" target="_blank" onclick="javascript:pageTracker._trackPageview('DOCUMENTS/<?php echo "{$row['id']}"; ?>'); "><img alt="" src="https://condosites.net/commons/txt.png" style="border: 0px solid;" border="0"></a><?php }; ?>
<?php if ($row['type'] == 'text/plain'){ ?><a href="../download-documents.php?id=<?php echo "{$row['id']}"; ?>&docdate=<?php echo "{$row['docdate']}"; ?>&conn=<?php echo $record['dbconnName'];?>&size=<?php echo "{$row['size']}"; ?>" target="_blank" onclick="javascript:pageTracker._trackPageview('DOCUMENTS/<?php echo "{$row['id']}"; ?>'); "><img alt="" src="https://condosites.net/commons/txt.png" style="border: 0px solid;" border="0"></a><?php }; ?>
<?php if ($row['type'] == 'text/html'){ ?><a href="../download-documents.php?id=<?php echo "{$row['id']}"; ?>&docdate=<?php echo "{$row['docdate']}"; ?>&conn=<?php echo $record['dbconnName'];?>&size=<?php echo "{$row['size']}"; ?>" target="_blank" onclick="javascript:pageTracker._trackPageview('DOCUMENTS/<?php echo "{$row['id']}"; ?>'); "><img alt="" src="https://condosites.net/commons/txt.png" style="border: 0px solid;" border="0"></a><?php }; ?>
<?php if ($row['type'] == 'application/vnd.openxmlformats'){ ?><a href="../download-documents.php?id=<?php echo "{$row['id']}"; ?>&docdate=<?php echo "{$row['docdate']}"; ?>&conn=<?php echo $record['dbconnName'];?>&size=<?php echo "{$row['size']}"; ?>" target="_blank" onclick="javascript:pageTracker._trackPageview('DOCUMENTS/<?php echo "{$row['id']}"; ?>'); "><img alt="" src="https://condosites.net/commons/word.png" style="border: 0px solid;" border="0"></a><?php }; ?>
<?php if ($row['type'] == 'application/msword'){ ?><a href="../download-documents.php?id=<?php echo "{$row['id']}"; ?>&docdate=<?php echo "{$row['docdate']}"; ?>&conn=<?php echo $record['dbconnName'];?>&size=<?php echo "{$row['size']}"; ?>" target="_blank" onclick="javascript:pageTracker._trackPageview('DOCUMENTS/<?php echo "{$row['id']}"; ?>'); "><img alt="" src="https://condosites.net/commons/word.png" style="border: 0px solid;" border="0"></a><?php }; ?>
<?php if ($row['type'] == 'application/vnd.ms-excel'){ ?><a href="../download-documents.php?id=<?php echo "{$row['id']}"; ?>&docdate=<?php echo "{$row['docdate']}"; ?>&conn=<?php echo $record['dbconnName'];?>&size=<?php echo "{$row['size']}"; ?>" target="_blank" onclick="javascript:pageTracker._trackPageview('DOCUMENTS/<?php echo "{$row['id']}"; ?>'); "><img alt="" src="https://condosites.net/commons/excel.png" style="border: 0px solid;" border="0"></a><?php }; ?>
<?php if ($row['type'] == 'application/download'){ ?><a href="../download-documents.php?id=<?php echo "{$row['id']}"; ?>&docdate=<?php echo "{$row['docdate']}"; ?>&conn=<?php echo $record['dbconnName'];?>&size=<?php echo "{$row['size']}"; ?>" target="_blank" onclick="javascript:pageTracker._trackPageview('DOCUMENTS/<?php echo "{$row['id']}"; ?>'); "><img alt="" src="https://condosites.net/commons/other.png" style="border: 0px solid;" border="0"></a><?php }; ?>
<?php if ($row['type'] == 'application/octet-stream'){ ?><a href="../download-documents.php?id=<?php echo "{$row['id']}"; ?>&docdate=<?php echo "{$row['docdate']}"; ?>&conn=<?php echo $record['dbconnName'];?>&size=<?php echo "{$row['size']}"; ?>" target="_blank" onclick="javascript:pageTracker._trackPageview('DOCUMENTS/<?php echo "{$row['id']}"; ?>'); "><img alt="" src="https://condosites.net/commons/txt.png" style="border: 0px solid;" border="0"></a><?php }; ?>
<?php if ($row['type'] == 'application/zip'){ ?><a href="../download-documents.php?id=<?php echo "{$row['id']}"; ?>&docdate=<?php echo "{$row['docdate']}"; ?>&conn=<?php echo $record['dbconnName'];?>&size=<?php echo "{$row['size']}"; ?>" target="_blank" onclick="javascript:pageTracker._trackPageview('DOCUMENTS/<?php echo "{$row['id']}"; ?>'); "><img alt="" src="https://condosites.net/commons/zip.png" style="border: 0px solid;" border="0"></a><?php }; ?>
<?php if ($row['type'] == 'video/mp4'){ ?><a href="../download-documents.php?id=<?php echo "{$row['id']}"; ?>&docdate=<?php echo "{$row['docdate']}"; ?>&conn=<?php echo $record['dbconnName'];?>&size=<?php echo "{$row['size']}"; ?>" target="_blank" onclick="javascript:pageTracker._trackPageview('DOCUMENTS/<?php echo "{$row['id']}"; ?>'); "><img alt="" src="https://condosites.net/commons/mp4.png" style="border: 0px solid;" border="0"></a><?php }; ?>