<?php if ($row['type'] == 'application/pdf'){ ?><a href="download-documents-restricted.php?id=<?php echo "{$row['id']}"; ?>&date=<?php echo "{$row['date']}"; ?>&size=<?php echo "{$row['size']}"; ?>" onclick="javascript:pageTracker._trackPageview('DOCUMENTS-RESTRICTED/<?php echo "{$row['id']}"; ?>'); "><img alt="" src="https://condosites.net/commons/pdf.png" border="0"></a><?php }; ?>
<?php if ($row['type'] == 'image/jpeg'){ ?><a href="download-documents-restricted.php?id=<?php echo "{$row['id']}"; ?>&date=<?php echo "{$row['date']}"; ?>&size=<?php echo "{$row['size']}"; ?>" onclick="javascript:pageTracker._trackPageview('DOCUMENTS-RESTRICTED/<?php echo "{$row['id']}"; ?>'); "><img alt="" src="https://condosites.net/commons/pictures.png" style="border: 0px solid;" border="0"></a><?php }; ?>
<?php if ($row['type'] == 'image/pjpeg'){ ?><a href="download-documents-restricted.php?id=<?php echo "{$row['id']}"; ?>&date=<?php echo "{$row['date']}"; ?>&size=<?php echo "{$row['size']}"; ?>" onclick="javascript:pageTracker._trackPageview('DOCUMENTS-RESTRICTED/<?php echo "{$row['id']}"; ?>'); "><img alt="" src="https://condosites.net/commons/pictures.png" style="border: 0px solid;" border="0"></a><?php }; ?>
<?php if ($row['type'] == 'image/gif'){ ?><a href="download-documents-restricted.php?id=<?php echo "{$row['id']}"; ?>&date=<?php echo "{$row['date']}"; ?>&size=<?php echo "{$row['size']}"; ?>" onclick="javascript:pageTracker._trackPageview('DOCUMENTS-RESTRICTED/<?php echo "{$row['id']}"; ?>'); "><img alt="" src="https://condosites.net/commons/pictures.png" style="border: 0px solid;" border="0"></a><?php }; ?>
<?php if ($row['type'] == 'image/png'){ ?><a href="download-documents-restricted.php?id=<?php echo "{$row['id']}"; ?>&date=<?php echo "{$row['date']}"; ?>&size=<?php echo "{$row['size']}"; ?>" onclick="javascript:pageTracker._trackPageview('DOCUMENTS-RESTRICTED/<?php echo "{$row['id']}"; ?>'); "><img alt="" src="https://condosites.net/commons/pictures.png" style="border: 0px solid;" border="0"></a><?php }; ?>
<?php if ($row['type'] == 'application/rtf'){ ?><a href="download-documents-restricted.php?id=<?php echo "{$row['id']}"; ?>&date=<?php echo "{$row['date']}"; ?>&size=<?php echo "{$row['size']}"; ?>" onclick="javascript:pageTracker._trackPageview('DOCUMENTS-RESTRICTED/<?php echo "{$row['id']}"; ?>'); "><img alt="" src="https://condosites.net/commons/txt.png" style="border: 0px solid;" border="0"></a><?php }; ?>
<?php if ($row['type'] == 'text/plain'){ ?><a href="download-documents-restricted.php?id=<?php echo "{$row['id']}"; ?>&date=<?php echo "{$row['date']}"; ?>&size=<?php echo "{$row['size']}"; ?>" onclick="javascript:pageTracker._trackPageview('DOCUMENTS-RESTRICTED/<?php echo "{$row['id']}"; ?>'); "><img alt="" src="https://condosites.net/commons/txt.png" style="border: 0px solid;" border="0"></a><?php }; ?>
<?php if ($row['type'] == 'application/msword'){ ?><a href="download-documents-restricted.php?id=<?php echo "{$row['id']}"; ?>&date=<?php echo "{$row['date']}"; ?>&size=<?php echo "{$row['size']}"; ?>" onclick="javascript:pageTracker._trackPageview('DOCUMENTS-RESTRICTED/<?php echo "{$row['id']}"; ?>'); "><img alt="" src="https://condosites.net/commons/word.png" style="border: 0px solid;" border="0"></a><?php }; ?>
<?php if ($row['type'] == 'application/download'){ ?><a href="download-documents-restricted.php?id=<?php echo "{$row['id']}"; ?>&date=<?php echo "{$row['date']}"; ?>&size=<?php echo "{$row['size']}"; ?>" onclick="javascript:pageTracker._trackPageview('DOCUMENTS-RESTRICTED/<?php echo "{$row['id']}"; ?>'); "><img alt="" src="https://condosites.net/commons/other.png" style="border: 0px solid;" border="0"></a><?php }; ?>
<?php if ($row['type'] == 'application/octet-stream'){ ?><a href="download-documents-restricted.php?id=<?php echo "{$row['id']}"; ?>&date=<?php echo "{$row['date']}"; ?>&size=<?php echo "{$row['size']}"; ?>" onclick="javascript:pageTracker._trackPageview('DOCUMENTS-RESTRICTED/<?php echo "{$row['id']}"; ?>'); "><img alt="" src="https://condosites.net/commons/txt.png" style="border: 0px solid;" border="0"></a><?php }; ?>
<?php if ($row['type'] == 'application/zip'){ ?><a href="download-documents-restricted.php?id=<?php echo "{$row['id']}"; ?>&date=<?php echo "{$row['date']}"; ?>&size=<?php echo "{$row['size']}"; ?>" onclick="javascript:pageTracker._trackPageview('DOCUMENTS-RESTRICTED/<?php echo "{$row['id']}"; ?>'); "><img alt="" src="https://condosites.net/commons/zip.png" style="border: 0px solid;" border="0"></a><?php }; ?>