<!-- PACKAGES -->
<?php if ($row['packagetype'] == 'UPS Package'){ ?><a href="http://wwwapps.ups.com/WebTracking/processRequest?HTMLVersion=5.0&Requester=NES&AgreeToTermsAndConditions=yes&loc=en_US&tracknum=<?php echo "{$row['pkgtracking']}"; ?>" target="_blank"><img alt="" src="https://condosites.net//commons/packages/ups.png" width="75" height="75" border="0"></a><?php }; ?>
<?php if ($row['packagetype'] == 'UPS Express Package'){ ?><a href="http://wwwapps.ups.com/WebTracking/processRequest?HTMLVersion=5.0&Requester=NES&AgreeToTermsAndConditions=yes&loc=en_US&tracknum=<?php echo "{$row['pkgtracking']}"; ?>" target="_blank"><img alt="" src="https://condosites.net//commons/packages/ups.png" width="75" height="75" border="0"></a><?php }; ?>
<?php if ($row['packagetype'] == 'UPS Ground Package'){ ?><a href="http://wwwapps.ups.com/WebTracking/processRequest?HTMLVersion=5.0&Requester=NES&AgreeToTermsAndConditions=yes&loc=en_US&tracknum=<?php echo "{$row['pkgtracking']}"; ?>" target="_blank"><img alt="" src="https://condosites.net//commons/packages/ups.png" width="75" height="75" border="0"></a><?php }; ?>
<?php if ($row['packagetype'] == 'FedEx Package'){ ?><a href="http://www.fedex.com/Tracking?action=track&tracknumbers=<?php echo "{$row['pkgtracking']}"; ?>" target="_blank"><img alt="" src="https://condosites.net//commons/packages/fedex.png" width="75" height="75" border="0"></a><?php }; ?>
<?php if ($row['packagetype'] == 'FedEx Express Package'){ ?><a href="http://www.fedex.com/Tracking?action=track&tracknumbers=<?php echo "{$row['pkgtracking']}"; ?>" target="_blank"><img alt="" src="https://condosites.net//commons/packages/fedexexpress.png" width="75" height="75" border="0"></a><?php }; ?>
<?php if ($row['packagetype'] == 'FedEx Ground Package'){ ?><a href="http://www.fedex.com/Tracking?action=track&tracknumbers=<?php echo "{$row['pkgtracking']}"; ?>" target="_blank"><img alt="" src="https://condosites.net//commons/packages/fedexground.png" width="75" height="75" border="0"></a><?php }; ?>
<?php if ($row['packagetype'] == 'DHL Package'){ ?><a href="http://track.dhl-usa.com/TrackByNbr.asp?ShipmentNumber=<?php echo "{$row['pkgtracking']}"; ?>" target="_blank"><img alt="" src="https://condosites.net//commons/packages/dhl.png" width="75" height="75" border="0"></a><?php }; ?>
<?php if ($row['packagetype'] == 'Amazon Package'){ ?><a href="http://www.amazon.com/gp/help/customer/display.html?nodeId=201182000" target="_blank"><img alt="" src="https://condosites.net//commons/packages/amazon.png" width="75" height="75" border="0"></a><?php }; ?>
<?php if ($row['packagetype'] == 'LaserShip Package'){ ?><a href="http://www.lasership.com/track.php?track_number_input=<?php echo "{$row['pkgtracking']}"; ?>" target="_blank"><img alt="" src="https://condosites.net//commons/packages/lasership.png" width="75" height="75" border="0"></a><?php }; ?>
<?php if ($row['packagetype'] == 'OnTrac Package'){ ?><a href="http://www.ontrac.com/tracking.asp?trackingres=submit&tracking_number=<?php echo "{$row['pkgtracking']}"; ?>" target="_blank"><img alt="" src="https://condosites.net//commons/packages/ontrac.png" width="75" height="75" border="0"></a><?php }; ?>
<?php if ($row['packagetype'] == 'USPS Package'){ ?><a href="http://trkcnfrm1.smi.usps.com/PTSInternetWeb/InterLabelInquiry.do?origTrackNum=<?php echo "{$row['pkgtracking']}"; ?>" target="_blank"><img alt="" src="https://condosites.net//commons/packages/usps.png" width="75" height="75" border="0"></a><?php }; ?>
<?php if ($row['packagetype'] == 'USPS Certified Letter'){ ?><a href="http://trkcnfrm1.smi.usps.com/PTSInternetWeb/InterLabelInquiry.do?origTrackNum=<?php echo "{$row['pkgtracking']}"; ?>" target="_blank"><img alt="" src="https://condosites.net//commons/packages/usps.png" width="75" height="75" border="0"></a><?php }; ?>
<?php if ($row['packagetype'] == 'USPS Express Mail'){ ?><a href="http://trkcnfrm1.smi.usps.com/PTSInternetWeb/InterLabelInquiry.do?origTrackNum=<?php echo "{$row['pkgtracking']}"; ?>" target="_blank"><img alt="" src="https://condosites.net//commons/packages/uspsexpress.png" width="75" height="75" border="0"></a><?php }; ?>
<?php if ($row['packagetype'] == 'USPS Priority Mail'){ ?><a href="http://trkcnfrm1.smi.usps.com/PTSInternetWeb/InterLabelInquiry.do?origTrackNum=<?php echo "{$row['pkgtracking']}"; ?>" target="_blank"><img alt="" src="https://condosites.net//commons/packages/uspspriority.png" width="75" height="75" border="0"></a><?php }; ?>
<?php if ($row['packagetype'] == 'USPS Registered Letter'){ ?><a href="http://trkcnfrm1.smi.usps.com/PTSInternetWeb/InterLabelInquiry.do?origTrackNum=<?php echo "{$row['pkgtracking']}"; ?>" target="_blank"><img alt="" src="https://condosites.net//commons/packages/usps.png" width="75" height="75" border="0"></a><?php }; ?>
<!-- DELIVERIES -->
<?php if ($row['packagetype'] == 'Delivery'){ ?><img alt="" src="https://condosites.net//commons/packages/delivery.png" width="75" height="75" border="0"><?php }; ?>
<?php if ($row['packagetype'] == 'Dry Cleaning Delivery'){ ?><img alt="" src="https://condosites.net//commons/packages/drycleaning.png" width="75" height="75" border="0"><?php }; ?>
<?php if ($row['packagetype'] == 'Flower Delivery'){ ?><img alt="" src="https://condosites.net//commons/packages/flowers.png" width="75" height="75" border="0"><?php }; ?>
<?php if ($row['packagetype'] == 'Gift'){ ?><img alt="" src="https://condosites.net//commons/packages/gift.png" width="75" height="75" border="0"><?php }; ?>
<?php if ($row['packagetype'] == 'Grocery Delivery'){ ?><img alt="" src="https://condosites.net//commons/packages/groceries.png" width="75" height="75" border="0"><?php }; ?>
<?php if ($row['packagetype'] == 'Video'){ ?><img alt="" src="https://condosites.net//commons/packages/video.png" width="75" height="75" border="0"><?php }; ?>
